version: '3'
services:
  app:
    build: .
    ports:
      - "8043:5001"
    volumes:
      - sqlite-data:/usr/src/app/data
    environment:
      - NODE_ENV=production

volumes:
  sqlite-data:
    driver: local